//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMenu.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMenu.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one now.
        /// </summary>
        public static string ActionAddOneNow {
            get {
                return ResourceManager.GetString("ActionAddOneNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ActionBack {
            get {
                return ResourceManager.GetString("ActionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string ActionFinish {
            get {
                return ResourceManager.GetString("ActionFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ActionNext {
            get {
                return ResourceManager.GetString("ActionNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string ActionOk {
            get {
                return ResourceManager.GetString("ActionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string ActionSkip {
            get {
                return ResourceManager.GetString("ActionSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for your meal..
        /// </summary>
        public static string ErrorEmptyMealName {
            get {
                return ResourceManager.GetString("ErrorEmptyMealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Meals.
        /// </summary>
        public static string ErrorNotEnoughMeals {
            get {
                return ResourceManager.GetString("ErrorNotEnoughMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the camera service. The app may not have the required permissions..
        /// </summary>
        public static string ErrorOpeningCameraService {
            get {
                return ResourceManager.GetString("ErrorOpeningCameraService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string HintCelsius {
            get {
                return ResourceManager.GetString("HintCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose picture.
        /// </summary>
        public static string HintChoosePicture {
            get {
                return ResourceManager.GetString("HintChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        public static string HintCup {
            get {
                return ResourceManager.GetString("HintCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string HintFahrenheit {
            get {
                return ResourceManager.GetString("HintFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string HintFrom {
            get {
                return ResourceManager.GetString("HintFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallon.
        /// </summary>
        public static string HintGallon {
            get {
                return ResourceManager.GetString("HintGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        public static string HintGram {
            get {
                return ResourceManager.GetString("HintGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string HintHour {
            get {
                return ResourceManager.GetString("HintHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string HintHours {
            get {
                return ResourceManager.GetString("HintHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient name.
        /// </summary>
        public static string HintIngredientName {
            get {
                return ResourceManager.GetString("HintIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string HintKelvin {
            get {
                return ResourceManager.GetString("HintKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string HintKilogram {
            get {
                return ResourceManager.GetString("HintKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litre.
        /// </summary>
        public static string HintLiter {
            get {
                return ResourceManager.GetString("HintLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal name.
        /// </summary>
        public static string HintMealName {
            get {
                return ResourceManager.GetString("HintMealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name.
        /// </summary>
        public static string HintMenuName {
            get {
                return ResourceManager.GetString("HintMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millilitre.
        /// </summary>
        public static string HintMilliliter {
            get {
                return ResourceManager.GetString("HintMilliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string HintMinute {
            get {
                return ResourceManager.GetString("HintMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string HintMinutes {
            get {
                return ResourceManager.GetString("HintMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next five days.
        /// </summary>
        public static string HintNextFiveDays {
            get {
                return ResourceManager.GetString("HintNextFiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next seven days.
        /// </summary>
        public static string HintNextSevenDays {
            get {
                return ResourceManager.GetString("HintNextSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images found..
        /// </summary>
        public static string HintNoImagesFound {
            get {
                return ResourceManager.GetString("HintNoImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ingredients found.
        /// </summary>
        public static string HintNoIngredientsFound {
            get {
                return ResourceManager.GetString("HintNoIngredientsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals found.
        /// </summary>
        public static string HintNoMealsFound {
            get {
                return ResourceManager.GetString("HintNoMealsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No menus found.
        /// </summary>
        public static string HintNoMenusFound {
            get {
                return ResourceManager.GetString("HintNoMenusFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display.
        /// </summary>
        public static string HintNothingToDisplay {
            get {
                return ResourceManager.GetString("HintNothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        public static string HintOunce {
            get {
                return ResourceManager.GetString("HintOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        public static string HintPound {
            get {
                return ResourceManager.GetString("HintPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove meal.
        /// </summary>
        public static string HintRemoveMeal {
            get {
                return ResourceManager.GetString("HintRemoveMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for image.
        /// </summary>
        public static string HintSearchForImage {
            get {
                return ResourceManager.GetString("HintSearchForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from scratch.
        /// </summary>
        public static string HintStartFromScratch {
            get {
                return ResourceManager.GetString("HintStartFromScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap meal.
        /// </summary>
        public static string HintSwapMeal {
            get {
                return ResourceManager.GetString("HintSwapMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoon.
        /// </summary>
        public static string HintTablespoon {
            get {
                return ResourceManager.GetString("HintTablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take picture.
        /// </summary>
        public static string HintTakePicture {
            get {
                return ResourceManager.GetString("HintTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoon.
        /// </summary>
        public static string HintTeaspoon {
            get {
                return ResourceManager.GetString("HintTeaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string HintTo {
            get {
                return ResourceManager.GetString("HintTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        public static string HintToFrom {
            get {
                return ResourceManager.GetString("HintToFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a picture of your meal..
        /// </summary>
        public static string MessageAddMealPicture {
            get {
                return ResourceManager.GetString("MessageAddMealPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be configured in settings..
        /// </summary>
        public static string MessageChangeInSettings {
            get {
                return ResourceManager.GetString("MessageChangeInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your menu..
        /// </summary>
        public static string MessageConfigureMenu {
            get {
                return ResourceManager.GetString("MessageConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to delete this meal? This action cannot be undone..
        /// </summary>
        public static string MessageConfirmDeleteMeal {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to delete this meal? This action cannot be undone. {0} menu will also be deleted..
        /// </summary>
        public static string MessageConfirmDeleteMealMenu {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteMealMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to delete this meal? This action cannot be undone. {0} menus will also be deleted..
        /// </summary>
        public static string MessageConfirmDeleteMealMenus {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteMealMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to delete this menu? This action cannot be undone..
        /// </summary>
        public static string MessageConfirmDeleteMenu {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal added successfully..
        /// </summary>
        public static string MessageCreateMealSuccess {
            get {
                return ResourceManager.GetString("MessageCreateMealSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu created successfully..
        /// </summary>
        public static string MessageCreateMenuSuccess {
            get {
                return ResourceManager.GetString("MessageCreateMenuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious!.
        /// </summary>
        public static string MessageDelicious {
            get {
                return ResourceManager.GetString("MessageDelicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add a name for your ingredient..
        /// </summary>
        public static string MessageEnterIngredientName {
            get {
                return ResourceManager.GetString("MessageEnterIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add a name for your meal..
        /// </summary>
        public static string MessageEnterMealName {
            get {
                return ResourceManager.GetString("MessageEnterMealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add a name for your menu..
        /// </summary>
        public static string MessageEnterMenuName {
            get {
                return ResourceManager.GetString("MessageEnterMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great shot!.
        /// </summary>
        public static string MessageGreatShot {
            get {
                return ResourceManager.GetString("MessageGreatShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing up to 10 images for &quot;{0}&quot;..
        /// </summary>
        public static string MessageImageSearchResults {
            get {
                return ResourceManager.GetString("MessageImageSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string MessageLooksGood {
            get {
                return ResourceManager.GetString("MessageLooksGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t added enough meals yet to create a menu. At least 2 meals are required..
        /// </summary>
        public static string MessageNotEnoughMeals {
            get {
                return ResourceManager.GetString("MessageNotEnoughMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a time of day for the menu..
        /// </summary>
        public static string MessageSelectMenuTimeOfDay {
            get {
                return ResourceManager.GetString("MessageSelectMenuTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today: {0}.
        /// </summary>
        public static string MessageTodaysMeal {
            get {
                return ResourceManager.GetString("MessageTodaysMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow: {0}.
        /// </summary>
        public static string MessageTomorrowsMeal {
            get {
                return ResourceManager.GetString("MessageTomorrowsMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating meal....
        /// </summary>
        public static string MessagingCreatingMeal {
            get {
                return ResourceManager.GetString("MessagingCreatingMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating menu....
        /// </summary>
        public static string MessagingCreatingMenu {
            get {
                return ResourceManager.GetString("MessagingCreatingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting meal....
        /// </summary>
        public static string MessagingDeletingMeal {
            get {
                return ResourceManager.GetString("MessagingDeletingMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting menu....
        /// </summary>
        public static string MessagingDeletingMenu {
            get {
                return ResourceManager.GetString("MessagingDeletingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating menu....
        /// </summary>
        public static string MessagingGeneratingMenu {
            get {
                return ResourceManager.GetString("MessagingGeneratingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for images of {0}....
        /// </summary>
        public static string MessagingImageSearching {
            get {
                return ResourceManager.GetString("MessagingImageSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MessagingLoading {
            get {
                return ResourceManager.GetString("MessagingLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image....
        /// </summary>
        public static string MessagingLoadingImage {
            get {
                return ResourceManager.GetString("MessagingLoadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ingredients....
        /// </summary>
        public static string MessagingLoadingIngredients {
            get {
                return ResourceManager.GetString("MessagingLoadingIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading meals....
        /// </summary>
        public static string MessagingLoadingMeals {
            get {
                return ResourceManager.GetString("MessagingLoadingMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading menus....
        /// </summary>
        public static string MessagingLoadingMenus {
            get {
                return ResourceManager.GetString("MessagingLoadingMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading times of day....
        /// </summary>
        public static string MessagingLoadingTimesOfDay {
            get {
                return ResourceManager.GetString("MessagingLoadingTimesOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        public static string TitleAboutApp {
            get {
                return ResourceManager.GetString("TitleAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string TitleBreakfast {
            get {
                return ResourceManager.GetString("TitleBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Action.
        /// </summary>
        public static string TitleChooseAction {
            get {
                return ResourceManager.GetString("TitleChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date Range.
        /// </summary>
        public static string TitleChooseDateRange {
            get {
                return ResourceManager.GetString("TitleChooseDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Metric.
        /// </summary>
        public static string TitleChooseMetric {
            get {
                return ResourceManager.GetString("TitleChooseMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Meal?.
        /// </summary>
        public static string TitleConfirmDeleteMeal {
            get {
                return ResourceManager.GetString("TitleConfirmDeleteMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Menu?.
        /// </summary>
        public static string TitleConfirmDeleteMenu {
            get {
                return ResourceManager.GetString("TitleConfirmDeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ingredient.
        /// </summary>
        public static string TitleCreateIngredient {
            get {
                return ResourceManager.GetString("TitleCreateIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Meal.
        /// </summary>
        public static string TitleCreateMeal {
            get {
                return ResourceManager.GetString("TitleCreateMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Menu.
        /// </summary>
        public static string TitleCreateMenu {
            get {
                return ResourceManager.GetString("TitleCreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string TitleDinner {
            get {
                return ResourceManager.GetString("TitleDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleHelp {
            get {
                return ResourceManager.GetString("TitleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Search.
        /// </summary>
        public static string TitleImageSearch {
            get {
                return ResourceManager.GetString("TitleImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string TitleIngredients {
            get {
                return ResourceManager.GetString("TitleIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string TitleLunch {
            get {
                return ResourceManager.GetString("TitleLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string TitleMeals {
            get {
                return ResourceManager.GetString("TitleMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string TitleMenus {
            get {
                return ResourceManager.GetString("TitleMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Open Camera.
        /// </summary>
        public static string TitleOpenCameraFailed {
            get {
                return ResourceManager.GetString("TitleOpenCameraFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TitleProfile {
            get {
                return ResourceManager.GetString("TitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Meal.
        /// </summary>
        public static string TitleSelectMeal {
            get {
                return ResourceManager.GetString("TitleSelectMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperate Calculator.
        /// </summary>
        public static string TitleTemperatureCalculator {
            get {
                return ResourceManager.GetString("TitleTemperatureCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times of Day.
        /// </summary>
        public static string TitleTimesOfDay {
            get {
                return ResourceManager.GetString("TitleTimesOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Calculator.
        /// </summary>
        public static string TitleVolumeCalculator {
            get {
                return ResourceManager.GetString("TitleVolumeCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calculator.
        /// </summary>
        public static string TitleWeightCalculator {
            get {
                return ResourceManager.GetString("TitleWeightCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.qwant.com/api/search/images?count={0}&amp;q={1}&amp;t=images&amp;safesearch=0&amp;locale=en_US&amp;uiv=4.
        /// </summary>
        public static string UrlImageSearch {
            get {
                return ResourceManager.GetString("UrlImageSearch", resourceCulture);
            }
        }
    }
}
